
python tfidf1.py
python tfidf2.py
python tfidf3.py
python tfidf4.py
python tfidf5.py
python tfidf6.py
python tfidf7.py
python tfidf8.py
python tfidf9.py
python tfidf10.py
python tfidf11.py
python tfidf12.py
python tfidf13.py
python tfidf14.py
python tfidf15.py
python tfidf16.py
python tfidf17.py
python tfidf18.py
python tfidf19.py
python tfidf20.py
